{{- if .Values.awsCluster.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ include "zesty-k8s.externalSecret.awsCred" . }}"
  labels:
    app.kubernetes.io/instance: "{{ include "zesty-k8s.fullname" . }}"
    app.kubernetes.io/name: "{{ include "zesty-k8s.fullname" . }}"
spec:
  secretStoreRef:
    name: aws-secret-manager-secretstore
    kind: ClusterSecretStore
  target:
    name: {{ .Values.awsCluster.secretName }}
  dataFrom:
  - extract:
      key: zesty/access-credentials
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
{{- end }}
